### PR TITLE
feat(*): Allow React functional components

### PR DESCRIPTION
**Pull request by pavloko**
### Rational
The release of Hooks allows to avoid classes completely, so it might be reasonable to allow functions to be used as top level components.

### Changes
I've added a check  to make sure `cmp` is a function and since Angular's directives and components are passed as strings it should be safe to attribute that component to React.

[React does similar check internally](https://github.com/facebook/react/blob/769b1f270e1251d9dbdce0fcbd9e92e502d059b8/packages/react-reconciler/src/ReactFiber.js#L302) and `ui-router`'s heuristic with these changes included would be similar. 

@christopherthielen I'd appreciate your feedback on this.

### CODE REVIEW

**Comment by pahen** [comment]
This would be awesome to support.

**Comment by christopherthielen** [comment]
> since Angular's directives and components are passed as strings it should be safe to attribute that component to React.

👍 I'm honestly surprised this hasn't come up before!  I thought we already supported functional components.  Thanks a bunch 😄

**Comment by pahen** [comment]
This works for functional React components but it breaks if the component is using `React.memo` since it will be an object then and not a function. Using `$type: 'react'` works though 👍

**Comment by pavloko** [comment]
@pahen Do you think this is something `ui-router` should handle?

**Comment by pahen** [comment]
Yes, since using `React.memo` is very common and included in React I think it would be very nice if `ui-router` could support it out of the box @pavloko

**Comment by pavloko** [comment]
Sounds good! I'll try to experiment with it sometime in the next 2 weeks.

**Pull request merged**
