### PR TITLE
Bump @uirouter/react dependency

### PR DESCRIPTION
**Pull request by pahen**
Use `@uirouter/react` 1.0.7 to support React 17

### CODE REVIEW

**Comment by pahen** [comment]
Would be awesome if this can be merged and published to NPM so we can upgrade our project to React 17 🎉  @christopherthielen

**Comment by pahen** [comment]
Maybe it should use `"~1.0.7"` instead of `"1.0.7"` @christopherthielen ?

**Comment by christopherthielen** [comment]
let's merge and release as-is.  We'll probably end up bumping dependencies and releasing a bunch of packages when the monorepo work is completed.

**Comment by pahen** [comment]
Awesome! Thanks! 🙏

**Pull request merged**
