### PR TITLE
Add Suport for componentProvider

### PR DESCRIPTION
**Pull request by jutaz**
Adds support for `componentProvider` feature that angularJS's version of router has. It will hijack the property, attaches its own provider and then updates the `component` definition from that.

### CODE REVIEW

**Comment by jutaz** [comment]
cc @christopherthielen I think this could be merged, as it's likely still relevant

**Comment by christopherthielen** [comment]
@jutaz Thanks for this PR and sorry I haven't noticed it earlier!

There's a problem with this implementation, however.  By mutating the view and assigning the `component`  property, it causes the `componentProvider` to not be called again the second time the state is loaded.

It's been a long time since I've been in this code, so I'm not sure what the proper approach is off the top of my head.

**Comment by jutaz** [comment]
Oh that’s interesting - lemme do some experiments on this. Mind sharing example, if you have any, with which I could reproduce the behavior you’re describing?


FWIW we’ve been running this code in production since this PR was opened.

**Comment by christopherthielen** [comment]
yeah I wrote some integration tests here: https://github.com/ui-router/react-hybrid/compare/jutaz-feature-support-componentProvider

Run using `npm run test:downstream`.  After doing that you can run them interactively (cypress) using `cd .downstream_tests/example ; npm run test:open`

**Comment by christopherthielen** [comment]
Actually, as I think about it, I don't believe `componentProvider` is necessary in ui-router/react with functional components.  


```js
var state =  {
    name: 'reactComponentProvider',
    url: '/reactComponentProvider/:component',

    component: props => {
      const componentName = props.transition.params().component;
      if (componentName === 'ReactComponent') {
        return <ReactComponent {...props} />;
      } else if (componentName === 'ReactFunctionalComponent') {
        return <ReactFunctionalComponent {...props} />;
      }
    }
  }
```

**Comment by jutaz** [comment]
Ahh, see in our case this is used in the hybrid router, where we switch between react & angular version of the components - thus the provider is needed:
```js
views: {
  $default: {
    componentProvider: ['featureFlagX', (featureFlagX) => {
      if (featureFlagX) {
        // React component, new functionality.
        return forRouterSafely(Zones);
      }
      // Legacy implementation in angular.
      return 'zoneSettings';
    }]
  }
}
```

So the provider is needed specifically to support the switching behavior, as there is no other good way to do that on the router level AFAIK.

**Comment by christopherthielen** [comment]
@jutaz aah, that makes perfect sense.   Are your feature flags known statically, or do you have to fetch them async?  If it's static, a state decorator could be used.  componentProvider is intended to switch components dynamically (because of this, I can't merge the PR as-is as it will effectively break the contract of componentProvider).

**Pull request closed without merging**
