### PR TITLE
chore(package): Bump @ui-router/react from 0.8.9 to 0.8.10

### PR DESCRIPTION
**Pull request by pahen**
Needed for React.StrictMode support added in https://github.com/ui-router/react/releases/tag/0.8.10

### CODE REVIEW

**Comment by pahen** [comment]
Hmm , the failing tests tells me this was not as easy as I thought :(

**Comment by christopherthielen** [comment]
we just have to bump all the dependencies in lock-step so the core module aligns.  

`@uirouter/core@6.0.1` and `@uirouter/angularjs@1.0.23` 👍

**Comment by pahen** [comment]
Aha, sweet :) Get passed the tests now but it fails at `yarn test:downstream`

**Comment by pahen** [comment]
I'm away for the weekend but I'll take a look when I'm back if you haven't solved it already

**Comment by christopherthielen** [comment]
this looks like it could be a bug in my tooling `check_peer_dependencies`

**Comment by christopherthielen** [comment]
weird, this passes locally.

**Comment by pahen** [comment]
Thanks! Works as expected :)

**Pull request merged**
